export type CaseType = 'Functional' | 'Negative' | 'Edge' | 'Security';
export type Priority = 'Critical' | 'High' | 'Medium' | 'Low';
export type AutomationStatus = 'Automated' | 'Manual' | 'Planned';
export type Layer = 'UI' | 'API' | 'Manual';
export type ExecutionStatus = 'Pass' | 'Documented Finding' | 'Not Executed';
export type Module = 'Login' | 'Cart & Checkout';

export interface Requirement {
  id: string;
  module: Module;
  description: string;
}

export const REQUIREMENTS: Requirement[] = [
  {
    id: 'REQ-LOGIN-AUTH',
    module: 'Login',
    description: 'Users can authenticate with valid credentials and the session persists across navigation and reload.',
  },
  {
    id: 'REQ-LOGIN-LOGOUT',
    module: 'Login',
    description: 'Users can log out and the app returns to a logged-out state.',
  },
  {
    id: 'REQ-LOGIN-VALIDATE',
    module: 'Login',
    description: 'The login form enforces required fields client-side before any network call.',
  },
  {
    id: 'REQ-LOGIN-NEGATIVE',
    module: 'Login',
    description: 'Invalid credentials (unknown user, wrong password, wrong case, untrimmed whitespace) are rejected with an accurate message.',
  },
  {
    id: 'REQ-LOGIN-SECURITY',
    module: 'Login',
    description: 'The login flow resists injection/XSS payloads and forged session tokens, and does not leak more than necessary via enumeration or brute force.',
  },
  {
    id: 'REQ-LOGIN-RESILIENCE',
    module: 'Login',
    description: 'The login flow tolerates oversized/unicode input and upstream API failure without crashing.',
  },
  {
    id: 'REQ-LOGIN-UX',
    module: 'Login',
    description: 'Non-authentication login-modal affordances (cancel, password masking) behave as expected.',
  },
  {
    id: 'REQ-CART-ADD',
    module: 'Cart & Checkout',
    description: 'Products can be added to the cart from the product page, including repeat adds.',
  },
  {
    id: 'REQ-CART-VIEW',
    module: 'Cart & Checkout',
    description: 'The cart accurately lists its contents and computes a correct total, including multi-item sums.',
  },
  {
    id: 'REQ-CART-DELETE',
    module: 'Cart & Checkout',
    description: 'Individual items can be removed from the cart, correctly updating rows and total.',
  },
  {
    id: 'REQ-CART-IDENTITY',
    module: 'Cart & Checkout',
    description: 'Cart contents are correctly scoped and isolated per guest/account identity, and persist appropriately across login/logout.',
  },
  {
    id: 'REQ-CART-CHECKOUT-VALIDATE',
    module: 'Cart & Checkout',
    description: 'The checkout form enforces its required fields, and gaps in that validation (format/expiry/whitespace) are documented rather than assumed.',
  },
  {
    id: 'REQ-CART-CHECKOUT-SUBMIT',
    module: 'Cart & Checkout',
    description: 'A valid order can be submitted, cancelled, or double-submitted safely, and clears the cart on success.',
  },
  {
    id: 'REQ-CART-SECURITY',
    module: 'Cart & Checkout',
    description: 'Checkout resists XSS payloads and price tampering, and does not unnecessarily expose sensitive card data.',
  },
  {
    id: 'REQ-CART-RESILIENCE',
    module: 'Cart & Checkout',
    description: 'Checkout tolerates oversized input without crashing.',
  },
];

export interface TestCaseRow {
  id: string;
  requirementId: string;
  module: Module;
  scenario: string;
  type: CaseType;
  priority: Priority;
  preconditions: string;
  testData: string;
  steps: string;
  expectedResult: string;
  postconditions: string;
  automationStatus: AutomationStatus;
  layer: Layer;
  suiteTags: string;
  browserScope: string;
  automationRef: string;
  observedResult: string;
  executionStatus: ExecutionStatus;
  defectId: string;
  owner: string;
  lastReviewed: string;
}

const OWNER = 'Bach Nguyen — QA Automation';
const REVIEWED = '2026-08-10';
const ALL_PROJECTS = 'chromium, firefox, webkit, mobile-chrome';

export const LOGIN_TEST_CASES: TestCaseRow[] = [
  {
    id: 'TC-LOGIN-01',
    requirementId: 'REQ-LOGIN-AUTH',
    module: 'Login',
    scenario: 'Valid credentials log the user in',
    type: 'Functional',
    priority: 'Critical',
    preconditions: 'A registered account exists (username/password known).',
    testData: 'username: <valid registered username>, password: <matching password>',
    steps: '1. Open the home page.\n2. Click "Log in" in the nav bar.\n3. Enter a valid username and password.\n4. Click "Log in".',
    expectedResult: 'Modal closes; nav bar shows "Welcome <username>" and a "Log out" link; "Log in" link is hidden.',
    postconditions: 'User remains logged in for the rest of the test.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@smoke @regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-01',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-02',
    requirementId: 'REQ-LOGIN-LOGOUT',
    module: 'Login',
    scenario: 'Logging out returns to the logged-out state',
    type: 'Functional',
    priority: 'High',
    preconditions: 'User is logged in.',
    testData: 'n/a',
    steps: '1. Click "Log out" in the nav bar.',
    expectedResult: '"Log in" / "Sign up" links reappear; the welcome label is hidden.',
    postconditions: 'User is logged out.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-02',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-03',
    requirementId: 'REQ-LOGIN-AUTH',
    module: 'Login',
    scenario: 'Session survives navigating to another page',
    type: 'Functional',
    priority: 'Medium',
    preconditions: 'User is logged in.',
    testData: 'n/a',
    steps: '1. Log in.\n2. Click "Cart" in the nav bar.',
    expectedResult: 'The cart page still shows "Welcome <username>" — login state is not lost on navigation.',
    postconditions: 'User remains logged in on the cart page.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-03',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-04',
    requirementId: 'REQ-LOGIN-NEGATIVE',
    module: 'Login',
    scenario: 'A non-existent username is rejected',
    type: 'Negative',
    priority: 'High',
    preconditions: 'The chosen username does not exist in the system.',
    testData: 'username: <random unregistered username>, password: irrelevant-password',
    steps: '1. Open the login modal.\n2. Enter a username that has never been registered.\n3. Enter any password.\n4. Click "Log in".',
    expectedResult: 'An alert reading "User does not exist." is shown; the user is not logged in.',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-04',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-05',
    requirementId: 'REQ-LOGIN-NEGATIVE',
    module: 'Login',
    scenario: 'The correct username with the wrong password is rejected',
    type: 'Negative',
    priority: 'High',
    preconditions: 'A registered account exists.',
    testData: 'username: <valid username>, password: <valid password> + "-wrong"',
    steps: '1. Open the login modal.\n2. Enter the correct username.\n3. Enter an incorrect password.\n4. Click "Log in".',
    expectedResult: 'An alert reading "Wrong password." is shown; the user is not logged in.',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-05',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-06',
    requirementId: 'REQ-LOGIN-VALIDATE',
    module: 'Login',
    scenario: 'Submitting with both fields empty is rejected client-side',
    type: 'Negative',
    priority: 'Medium',
    preconditions: 'None.',
    testData: 'username: "", password: ""',
    steps: '1. Open the login modal.\n2. Leave both fields empty.\n3. Click "Log in".',
    expectedResult: 'An alert reading "Please fill out Username and Password." is shown before any network call; the modal stays open.',
    postconditions: 'Modal remains open.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-06',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-07',
    requirementId: 'REQ-LOGIN-VALIDATE',
    module: 'Login',
    scenario: 'Submitting with only the password filled is rejected client-side',
    type: 'Negative',
    priority: 'Medium',
    preconditions: 'None.',
    testData: 'username: "", password: <valid password>',
    steps: '1. Open the login modal.\n2. Leave username empty; fill in a password.\n3. Click "Log in".',
    expectedResult: 'Same client-side validation alert as TC-LOGIN-06.',
    postconditions: 'Modal remains open.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-07',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-08',
    requirementId: 'REQ-LOGIN-SECURITY',
    module: 'Login',
    scenario: 'A SQL-injection-shaped username is treated as plain text, not exploited',
    type: 'Security',
    priority: 'High',
    preconditions: 'None.',
    testData: "username: <run-unique prefix>' OR '1'='1' --, password: ' OR '1'='1' --",
    steps: "1. Open the login modal.\n2. Enter a run-unique-prefixed ' OR '1'='1' -- as the username, and the raw payload as the password.\n3. Click \"Log in\".",
    expectedResult:
      'Treated as an ordinary, unrecognized username: an alert reading "User does not exist." is shown; no SQL error, no crash, and — critically — no bypassed login.',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@edge @security @regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-08',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-09',
    requirementId: 'REQ-LOGIN-RESILIENCE',
    module: 'Login',
    scenario: 'A very long username is handled without crashing the page',
    type: 'Edge',
    priority: 'Low',
    preconditions: 'None.',
    testData: "username: 'a'.repeat(500), password: irrelevant-password",
    steps: '1. Open the login modal.\n2. Enter a 500-character username.\n3. Click "Log in".',
    expectedResult: 'An error alert is shown (not a crash); the page remains responsive.',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@edge',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-09',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-10',
    requirementId: 'REQ-LOGIN-NEGATIVE',
    module: 'Login',
    scenario: 'Username lookup is case-sensitive',
    type: 'Edge',
    priority: 'Medium',
    preconditions: 'A registered account exists.',
    testData: 'username: <VALID USERNAME UPPERCASED>, password: <valid password>',
    steps: '1. Open the login modal.\n2. Enter the registered username in uppercase.\n3. Enter the correct password.\n4. Click "Log in".',
    expectedResult: 'Rejected with "User does not exist." — documents actual behavior (no case-folding) rather than assuming it.',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@edge @regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-10',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-11',
    requirementId: 'REQ-LOGIN-VALIDATE',
    module: 'Login',
    scenario: 'Only username filled, password empty is rejected',
    type: 'Negative',
    priority: 'Low',
    preconditions: 'None.',
    testData: 'username: <valid username>, password: ""',
    steps: '1. Open the login modal.\n2. Fill in a username; leave password empty.\n3. Click "Log in".',
    expectedResult: 'Same "Please fill out Username and Password." alert as TC-LOGIN-06/07.',
    postconditions: 'Modal remains open.',
    automationStatus: 'Manual',
    layer: 'Manual',
    suiteTags: 'n/a — documented only',
    browserScope: 'n/a',
    automationRef: 'Not automated — symmetric case of TC-LOGIN-07, same client-side validation code path.',
    observedResult: '',
    executionStatus: 'Not Executed',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-12',
    requirementId: 'REQ-LOGIN-NEGATIVE',
    module: 'Login',
    scenario: 'Leading/trailing whitespace in credentials is treated literally (not trimmed)',
    type: 'Edge',
    priority: 'Low',
    preconditions: 'A registered account exists.',
    testData: 'username: " <valid username>", password: <valid password>',
    steps: '1. Open the login modal.\n2. Enter the valid username with a leading space.\n3. Enter the valid password.\n4. Click "Log in".',
    expectedResult: 'Rejected as an unknown user — the app does not trim whitespace before lookup.',
    postconditions: 'None.',
    automationStatus: 'Manual',
    layer: 'Manual',
    suiteTags: 'n/a — documented only',
    browserScope: 'n/a',
    automationRef: 'Documented for manual/exploratory verification.',
    observedResult: '',
    executionStatus: 'Not Executed',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-13',
    requirementId: 'REQ-LOGIN-UX',
    module: 'Login',
    scenario: 'Closing the login modal via the × button cancels without submitting',
    type: 'Functional',
    priority: 'Low',
    preconditions: 'None.',
    testData: 'n/a',
    steps: '1. Open the login modal.\n2. Enter any credentials.\n3. Click the × close button instead of "Log in".',
    expectedResult: 'Modal closes; no network request is made; user remains logged out.',
    postconditions: 'None.',
    automationStatus: 'Manual',
    layer: 'Manual',
    suiteTags: 'n/a — documented only',
    browserScope: 'n/a',
    automationRef: 'Documented for manual/exploratory verification.',
    observedResult: '',
    executionStatus: 'Not Executed',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-14',
    requirementId: 'REQ-LOGIN-SECURITY',
    module: 'Login',
    scenario: 'An XSS-shaped username is rendered as inert text, not executed',
    type: 'Security',
    priority: 'Medium',
    preconditions: 'None.',
    testData: 'username: <script>alert(1)</script>',
    steps: '1. Open the login modal.\n2. Enter <script>alert(1)</script> as the username.\n3. Submit.',
    expectedResult: 'No script executes; the string is handled as an ordinary (rejected) username.',
    postconditions: 'None.',
    automationStatus: 'Manual',
    layer: 'Manual',
    suiteTags: 'n/a — documented only',
    browserScope: 'n/a',
    automationRef: 'Documented for manual/exploratory verification — same family as TC-LOGIN-08. TC-CART-24 automates the equivalent payload against the checkout Name field.',
    observedResult: '',
    executionStatus: 'Not Executed',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-15',
    requirementId: 'REQ-LOGIN-UX',
    module: 'Login',
    scenario: 'Password characters are masked in the input field',
    type: 'Functional',
    priority: 'Low',
    preconditions: 'None.',
    testData: 'password: anything',
    steps: '1. Open the login modal.\n2. Type into the password field.',
    expectedResult: 'Characters render as dots/asterisks, not plain text.',
    postconditions: 'None.',
    automationStatus: 'Manual',
    layer: 'Manual',
    suiteTags: 'n/a — documented only',
    browserScope: 'n/a',
    automationRef: 'Documented for manual/exploratory verification (visual property, not a functional assertion).',
    observedResult: '',
    executionStatus: 'Not Executed',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-16',
    requirementId: 'REQ-LOGIN-RESILIENCE',
    module: 'Login',
    scenario: 'A Unicode/emoji username is handled without crashing',
    type: 'Edge',
    priority: 'Low',
    preconditions: 'None.',
    testData: 'username: 用户🙂test',
    steps: '1. Open the login modal.\n2. Enter a username containing emoji/non-Latin characters.\n3. Submit.',
    expectedResult: 'Rejected as an unknown user; page remains responsive, no crash.',
    postconditions: 'None.',
    automationStatus: 'Manual',
    layer: 'Manual',
    suiteTags: 'n/a — documented only',
    browserScope: 'n/a',
    automationRef: 'Documented for manual/exploratory verification.',
    observedResult: '',
    executionStatus: 'Not Executed',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-17',
    requirementId: 'REQ-LOGIN-AUTH',
    module: 'Login',
    scenario: 'Login session persists across a full page reload',
    type: 'Functional',
    priority: 'High',
    preconditions: 'User is logged in.',
    testData: 'n/a',
    steps: '1. Log in.\n2. Hard-reload the page (not an in-app navigation).',
    expectedResult:
      'The welcome label and "Log out" link are still shown after reload — verified against the live site: the session lives in a `tokenp_` cookie (not localStorage), so a reload re-sends it and the session is correctly re-resolved.',
    postconditions: 'User remains logged in.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-17',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-18',
    requirementId: 'REQ-LOGIN-SECURITY',
    module: 'Login',
    scenario: 'A forged session-token cookie is rejected, not trusted client-side',
    type: 'Security',
    priority: 'High',
    preconditions: 'None (starts logged out).',
    testData: 'tokenp_ cookie := base64("forged-admin_<timestamp>") — a value the server never issued',
    steps: '1. Load the site as a guest.\n2. Inject a forged `tokenp_` cookie with an arbitrary, never-issued value.\n3. Reload.',
    expectedResult:
      'The app does NOT show a logged-in state for the forged identity — verified against the live site: session resolution round-trips the token through POST /check server-side and rejects an unrecognized one, rather than trusting the cookie at face value.',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@security @edge',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-18',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-19',
    requirementId: 'REQ-LOGIN-SECURITY',
    module: 'Login',
    scenario: "Logging out clears the session token so it can't be silently restored on reload",
    type: 'Security',
    priority: 'High',
    preconditions: 'User is logged in.',
    testData: 'n/a',
    steps: '1. Log in.\n2. Log out.\n3. Inspect cookies, then reload.',
    expectedResult: 'The `tokenp_` cookie is gone after logout, and the reload still shows a logged-out state — the old session cannot be replayed just by refreshing.',
    postconditions: 'User remains logged out.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@security @regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-19',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-20',
    requirementId: 'REQ-LOGIN-RESILIENCE',
    module: 'Login',
    scenario: 'A very long password is handled without crashing the page',
    type: 'Edge',
    priority: 'Low',
    preconditions: 'None.',
    testData: "username: <random>, password: 'a'.repeat(500)",
    steps: '1. Open the login modal.\n2. Enter a normal username and a 500-character password.\n3. Click "Log in".',
    expectedResult: 'An error alert is shown (not a crash); the page remains responsive — the password-length symmetric case of TC-LOGIN-09.',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@edge',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-20',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-21',
    requirementId: 'REQ-LOGIN-SECURITY',
    module: 'Login',
    scenario: 'Repeated failed login attempts are not rate-limited or locked out',
    type: 'Security',
    priority: 'Medium',
    preconditions: 'A registered account exists.',
    testData: 'username: <valid username>, password: <20 sequential wrong passwords>',
    steps: '1. Submit the login form with the correct username and an incorrect password.\n2. Repeat with 20+ rapid attempts.\n3. Observe whether the account locks, a CAPTCHA appears, or requests start being throttled/refused.',
    expectedResult:
      'Risk to document, not to reproduce here: demoblaze.com is a real, shared public demo used by other testers, so deliberately hammering its login endpoint to find the actual threshold is out of scope for automation. Expected behavior for a production system would be a lockout/backoff after N attempts; record whatever threshold (if any) is observed during manual/exploratory review.',
    postconditions: 'None.',
    automationStatus: 'Manual',
    layer: 'Manual',
    suiteTags: 'n/a — documented only, intentionally not automated (see Read Me sheet)',
    browserScope: 'n/a',
    automationRef: 'Deliberately not automated — see "Read Me & Assumptions" sheet for the rationale (avoids load-testing a shared public demo site).',
    observedResult: '',
    executionStatus: 'Not Executed',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-22',
    requirementId: 'REQ-LOGIN-SECURITY',
    module: 'Login',
    scenario: 'Distinct error messages for "unknown user" vs. "wrong password" enable username enumeration',
    type: 'Security',
    priority: 'Medium',
    preconditions: 'A registered account exists.',
    testData: 'see TC-LOGIN-04 (unknown user) and TC-LOGIN-05 (wrong password)',
    steps: '1. Attempt login with an unregistered username (TC-LOGIN-04).\n2. Attempt login with a registered username and wrong password (TC-LOGIN-05).\n3. Compare the two error messages.',
    expectedResult: 'Both failures use the same generic message so the response does not disclose whether the username exists.',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@security @regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-22',
    observedResult: '"User does not exist." (unknown user) vs. "Wrong password." (known user, bad password) — distinguishable messages.',
    executionStatus: 'Documented Finding',
    defectId: 'DEF-LOGIN-02',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-LOGIN-23',
    requirementId: 'REQ-LOGIN-RESILIENCE',
    module: 'Login',
    scenario: 'A failing auth API leaves the login modal open without crashing the page',
    type: 'Negative',
    priority: 'Medium',
    preconditions: 'None.',
    testData: 'POST /login intercepted to return HTTP 500',
    steps: '1. Intercept POST /login to return a 500 error.\n2. Open the login modal, fill in any credentials, submit.',
    expectedResult: 'A clear, recoverable error is shown; the modal remains open, the user stays logged out, and the page remains usable.',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@edge @regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-23',
    observedResult: 'No dialog/alert is raised; #logInModal remains visible with no error text; page remains responsive.',
    executionStatus: 'Documented Finding',
    defectId: 'DEF-LOGIN-01',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
];

export const CART_TEST_CASES: TestCaseRow[] = [
  {
    id: 'TC-CART-01',
    requirementId: 'REQ-CART-ADD',
    module: 'Cart & Checkout',
    scenario: 'Adding a product surfaces a confirmation and lists it in the cart',
    type: 'Functional',
    priority: 'Critical',
    preconditions: 'None (works whether logged in or as a guest).',
    testData: 'product: Samsung galaxy s6',
    steps: '1. Open a product page.\n2. Click "Add to cart".\n3. Navigate to the cart page.',
    expectedResult: 'An alert confirms "Product added." (with or without trailing period); the product appears as exactly one row in the cart.',
    postconditions: 'Cart contains one item.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@smoke @regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-01',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-02',
    requirementId: 'REQ-CART-CHECKOUT-SUBMIT',
    module: 'Cart & Checkout',
    scenario: 'Full journey: log in, add to cart, place an order',
    type: 'Functional',
    priority: 'Critical',
    preconditions: 'A registered account exists.',
    testData: 'product: Samsung galaxy s6; name: QA Automation; card: 4111111111111111; month: 12; year: 2030',
    steps:
      '1. Log in.\n2. Clear any pre-existing cart contents.\n3. Add a product to the cart.\n4. Open "Place Order".\n5. Fill in Name, Country, City, Card, Month, Year.\n6. Click "Purchase".',
    expectedResult:
      'Cart total equals the product price; the Place Order total matches; purchase succeeds and shows a confirmation with a non-empty order ID, the correct amount, and the entered name.',
    postconditions: 'Cart is empty (purchase clears it — see TC-CART-18).',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@smoke @regression @e2e',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-02 (primary end-to-end demo scenario)',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-03',
    requirementId: 'REQ-CART-ADD',
    module: 'Cart & Checkout',
    scenario: 'Adding the same product twice creates two separate line items',
    type: 'Edge',
    priority: 'Medium',
    preconditions: 'None.',
    testData: 'product: Apple monitor 24',
    steps: '1. Open a product page.\n2. Click "Add to cart" twice in a row.\n3. Open the cart.',
    expectedResult: 'Two separate rows for the same product appear — demoblaze has no quantity/merge concept, documented rather than assumed.',
    postconditions: 'Cart contains two items.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@edge @regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-03',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-04',
    requirementId: 'REQ-CART-DELETE',
    module: 'Cart & Checkout',
    scenario: 'Deleting an item removes it from the cart',
    type: 'Functional',
    priority: 'High',
    preconditions: 'The cart contains at least one item.',
    testData: 'product: Sony vaio i5',
    steps: '1. Open the cart.\n2. Click "Delete" on a row.',
    expectedResult: 'The row disappears and the cart row count decreases by one.',
    postconditions: 'Row removed.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-04',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-05',
    requirementId: 'REQ-CART-CHECKOUT-VALIDATE',
    module: 'Cart & Checkout',
    scenario: 'Placing an order with Name and Card both empty is rejected client-side',
    type: 'Negative',
    priority: 'High',
    preconditions: 'The cart contains at least one item.',
    testData: 'name: "", card: ""',
    steps: '1. Open "Place Order".\n2. Fill only Country/City/Month/Year; leave Name and Card blank.\n3. Click "Purchase".',
    expectedResult: 'An alert reading "Please fill out Name and Creditcard." is shown; no confirmation dialog appears.',
    postconditions: 'Order modal remains open, no purchase made.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-05',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-06',
    requirementId: 'REQ-CART-CHECKOUT-VALIDATE',
    module: 'Cart & Checkout',
    scenario: 'Optional address/date fields can be left blank',
    type: 'Functional',
    priority: 'Medium',
    preconditions: 'The cart contains at least one item.',
    testData: 'name: Minimal Fields, card: 4111111111111111',
    steps: '1. Open "Place Order".\n2. Fill only Name and Card; leave Country/City/Month/Year blank.\n3. Click "Purchase".',
    expectedResult: 'Purchase succeeds; the confirmation shows the entered name — only Name/Card are truly required.',
    postconditions: 'Cart is empty (see TC-CART-18).',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@edge @regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-06',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-07',
    requirementId: 'REQ-CART-VIEW',
    module: 'Cart & Checkout',
    scenario: 'The cart total equals the sum of its line items',
    type: 'Functional',
    priority: 'Medium',
    preconditions: 'None.',
    testData: 'products: Samsung galaxy s6 + Sony vaio i5',
    steps: '1. Clear the cart.\n2. Add two different products.\n3. Open the cart and read the displayed total.',
    expectedResult: 'The displayed total exactly equals the sum of both products’ prices — a genuine sum, not a single-item total.',
    postconditions: 'Cart contains two items.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-07',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-08',
    requirementId: 'REQ-CART-IDENTITY',
    module: 'Cart & Checkout',
    scenario: 'The cart is reachable without being logged in',
    type: 'Edge',
    priority: 'Medium',
    preconditions: 'User is logged out.',
    testData: 'n/a',
    steps: '1. Navigate directly to /cart.html as a guest.',
    expectedResult: 'The cart page and checkout control render without requiring authentication.',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@edge @regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-08',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-09',
    requirementId: 'REQ-CART-CHECKOUT-VALIDATE',
    module: 'Cart & Checkout',
    scenario: 'A non-numeric card number is still accepted',
    type: 'Negative',
    priority: 'Low',
    preconditions: 'The cart contains at least one item.',
    testData: 'card: "not-a-card-number"',
    steps: '1. Open "Place Order".\n2. Fill Name and enter a non-numeric string as Card.\n3. Click "Purchase".',
    expectedResult: 'A format-validating checkout would reject this before submission.',
    postconditions: 'None.',
    automationStatus: 'Manual',
    layer: 'Manual',
    suiteTags: 'n/a — documented only',
    browserScope: 'n/a',
    automationRef: 'Documented finding — candidate for future automation once product owner confirms expected behavior.',
    observedResult: 'Purchase still succeeds — no card-format validation exists.',
    executionStatus: 'Not Executed',
    defectId: 'DEF-CART-01',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-10',
    requirementId: 'REQ-CART-CHECKOUT-VALIDATE',
    module: 'Cart & Checkout',
    scenario: 'An already-expired card year is still accepted',
    type: 'Negative',
    priority: 'Low',
    preconditions: 'The cart contains at least one item.',
    testData: 'year: 2010',
    steps: '1. Open "Place Order".\n2. Fill Name/Card, set Year to a year in the past.\n3. Click "Purchase".',
    expectedResult: 'A real checkout would reject an already-expired card.',
    postconditions: 'None.',
    automationStatus: 'Manual',
    layer: 'Manual',
    suiteTags: 'n/a — documented only',
    browserScope: 'n/a',
    automationRef: 'Documented finding — same category as TC-CART-09.',
    observedResult: 'Purchase still succeeds — no expiry validation exists.',
    executionStatus: 'Not Executed',
    defectId: 'DEF-CART-02',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-11',
    requirementId: 'REQ-CART-DELETE',
    module: 'Cart & Checkout',
    scenario: 'Deleting the only remaining item empties the cart total',
    type: 'Functional',
    priority: 'Low',
    preconditions: 'The cart contains exactly one item.',
    testData: 'n/a',
    steps: '1. Delete the last remaining row.',
    expectedResult: 'The row list is empty and the total label shows no value.',
    postconditions: 'Cart is empty.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-11',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-12',
    requirementId: 'REQ-CART-IDENTITY',
    module: 'Cart & Checkout',
    scenario: 'Guest carts are isolated between browser contexts',
    type: 'Security',
    priority: 'High',
    preconditions: 'None.',
    testData: 'n/a',
    steps: '1. Add a product to the cart as a guest in one browser context.\n2. Open a second, independent browser context as a fresh guest.\n3. Load the cart in the second context.',
    expectedResult:
      'The second context does NOT see the first context’s item. DemoBlaze scopes guest carts by a per-browser `user` cookie (set on first page load) and authenticated carts by the login token — verified against the live site by inspecting the `/addtocart` and `/viewcart` request bodies, not assumed.',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@edge @security @regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-12',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-13',
    requirementId: 'REQ-CART-VIEW',
    module: 'Cart & Checkout',
    scenario: 'Product page price matches the price shown in the cart row',
    type: 'Functional',
    priority: 'Low',
    preconditions: 'None.',
    testData: 'product: Samsung galaxy s6',
    steps: '1. Read the price on a product page.\n2. Add it to the cart.\n3. Compare against the price shown in the cart row.',
    expectedResult: 'The two prices match exactly.',
    postconditions: 'None.',
    automationStatus: 'Manual',
    layer: 'Manual',
    suiteTags: 'n/a — documented only',
    browserScope: 'n/a',
    automationRef: 'Implicitly covered by the price-equality assertions in TC-CART-02/07/27.',
    observedResult: '',
    executionStatus: 'Not Executed',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-14',
    requirementId: 'REQ-CART-CHECKOUT-VALIDATE',
    module: 'Cart & Checkout',
    scenario: 'Opening "Place Order" on an empty cart is not blocked',
    type: 'Negative',
    priority: 'Low',
    preconditions: 'The cart has been cleared.',
    testData: 'n/a',
    steps: '1. Clear the cart.\n2. Click "Place Order".',
    expectedResult: 'A guarded checkout would refuse to open on an empty cart.',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-14',
    observedResult: 'The modal still opens, with a total of 0 — there is no "cart is empty" guard.',
    executionStatus: 'Documented Finding',
    defectId: 'DEF-CART-06',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-15',
    requirementId: 'REQ-CART-CHECKOUT-VALIDATE',
    module: 'Cart & Checkout',
    scenario: 'Placing an order with only Name empty is rejected client-side',
    type: 'Negative',
    priority: 'High',
    preconditions: 'The cart contains at least one item.',
    testData: 'name: "", card: 4111111111111111',
    steps: '1. Open "Place Order".\n2. Leave Name blank; fill Card.\n3. Click "Purchase".',
    expectedResult: 'Same "Please fill out Name and Creditcard." alert as TC-CART-05 — the check does not distinguish which of the two is missing.',
    postconditions: 'Order modal remains open, no purchase made.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-15',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-16',
    requirementId: 'REQ-CART-CHECKOUT-VALIDATE',
    module: 'Cart & Checkout',
    scenario: 'Placing an order with only Card empty is rejected client-side',
    type: 'Negative',
    priority: 'High',
    preconditions: 'The cart contains at least one item.',
    testData: 'name: Card Missing, card: ""',
    steps: '1. Open "Place Order".\n2. Fill Name; leave Card blank.\n3. Click "Purchase".',
    expectedResult: 'Same "Please fill out Name and Creditcard." alert as TC-CART-05/15.',
    postconditions: 'Order modal remains open, no purchase made.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-16',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-17',
    requirementId: 'REQ-CART-CHECKOUT-SUBMIT',
    module: 'Cart & Checkout',
    scenario: 'Closing "Place Order" via the × button cancels without creating an order',
    type: 'Functional',
    priority: 'Medium',
    preconditions: 'The cart contains at least one item.',
    testData: 'n/a',
    steps: '1. Open "Place Order".\n2. Fill in valid Name/Card.\n3. Click the × close button instead of "Purchase".',
    expectedResult: 'The modal closes; no confirmation appears; the cart contents are unchanged.',
    postconditions: 'Cart contents unchanged.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-17',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-18',
    requirementId: 'REQ-CART-CHECKOUT-SUBMIT',
    module: 'Cart & Checkout',
    scenario: 'Completing a purchase clears the cart afterward',
    type: 'Functional',
    priority: 'High',
    preconditions: 'The cart contains at least one item.',
    testData: 'n/a',
    steps: '1. Add an item.\n2. Complete a purchase.\n3. Reopen the cart.',
    expectedResult: 'The cart is empty after a successful purchase — verified against the live site with a response-waited read (not a single racy check).',
    postconditions: 'Cart is empty.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-18',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-19',
    requirementId: 'REQ-CART-CHECKOUT-SUBMIT',
    module: 'Cart & Checkout',
    scenario: 'Rapid double-submit handling',
    type: 'Edge',
    priority: 'Medium',
    preconditions: 'The cart contains at least one item.',
    testData: 'n/a',
    steps: '1. Open "Place Order", fill Name/Card.\n2. Click "Purchase" twice as close together as possible.',
    expectedResult: 'Only one checkout submission is processed.',
    postconditions: 'Cart is empty (purchase clears it).',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@edge @known-issue',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-19',
    observedResult: 'Two POST /deletecart requests are sent when Purchase is triggered twice rapidly.',
    executionStatus: 'Documented Finding',
    defectId: 'DBZ-CART-001',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-20',
    requirementId: 'REQ-CART-SECURITY',
    module: 'Cart & Checkout',
    scenario: 'The purchase receipt displays the card number unmasked',
    type: 'Security',
    priority: 'Medium',
    preconditions: 'The cart contains at least one item.',
    testData: 'card: 4111111111111111',
    steps: '1. Complete a purchase with a full 16-digit card number.\n2. Read the "Card Number" field on the confirmation.',
    expectedResult: 'A PCI-conscious checkout would mask all but the last 4 digits (e.g. "**** **** **** 1111").',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@security',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-20',
    observedResult: 'The full, unmasked PAN is echoed back verbatim in the confirmation text.',
    executionStatus: 'Documented Finding',
    defectId: 'DEF-CART-03',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-21',
    requirementId: 'REQ-CART-SECURITY',
    module: 'Cart & Checkout',
    scenario: 'A modified product response controls the displayed checkout totals',
    type: 'Security',
    priority: 'Critical',
    preconditions: 'None.',
    testData: 'Intercepted POST /view response with `price` rewritten to 1',
    steps:
      '1. Intercept every POST /view response and rewrite its `price` field to 1 (the only network hop that carries a price — POST /addtocart never submits one).\n2. Add the product to the cart.\n3. Read the cart total, the order-modal total, and the final purchase Amount.',
    expectedResult: 'Displayed cart and confirmation totals remain consistent with a trusted product-price source, or the modified response is rejected.',
    postconditions: 'None.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@security @regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-21',
    observedResult: 'The modified $1 price propagates through the client-rendered cart total, order-modal total, and confirmation Amount. No backend order acceptance is asserted.',
    executionStatus: 'Documented Finding',
    defectId: 'DEF-CART-04',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-22',
    requirementId: 'REQ-CART-IDENTITY',
    module: 'Cart & Checkout',
    scenario: "A logged-in account's cart persists across logout and back in",
    type: 'Functional',
    priority: 'Medium',
    preconditions: 'A registered account exists.',
    testData: 'product: Samsung galaxy s6',
    steps: '1. Log in and add an item.\n2. Log out.\n3. Log back in with the same account.\n4. Reopen the cart.',
    expectedResult: 'The item added before logout is still present — the account cart is a durable per-account store, not a per-session one.',
    postconditions: 'Cart is cleared by the test as cleanup.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-22',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-23',
    requirementId: 'REQ-CART-IDENTITY',
    module: 'Cart & Checkout',
    scenario: 'A guest cart does not automatically merge into the account cart on login',
    type: 'Security',
    priority: 'Medium',
    preconditions: 'A registered account exists.',
    testData: 'product: Apple monitor 24',
    steps: '1. As a guest (same browser context), add an item.\n2. Log in with a registered account in that same context.\n3. Reopen the cart.',
    expectedResult:
      'The guest item does NOT appear under the now-logged-in account — guest and account carts are separate stores keyed by different identity cookies, confirmed against the live site rather than assumed either way.',
    postconditions: 'None (guest cart still holds the item; harmless, isolated per TC-CART-12).',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@security @edge @regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-23',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-24',
    requirementId: 'REQ-CART-SECURITY',
    module: 'Cart & Checkout',
    scenario: 'An XSS-shaped checkout Name is rendered as inert text, not executed',
    type: 'Security',
    priority: 'High',
    preconditions: 'The cart contains at least one item.',
    testData: 'name: <script>window.__xss=1</script>',
    steps: '1. Open "Place Order".\n2. Enter a <script> payload as the Name.\n3. Complete the purchase.',
    expectedResult: 'No script executes; the confirmation displays the payload as literal text, not markup.',
    postconditions: 'Cart is empty.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@security',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-24',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-25',
    requirementId: 'REQ-CART-RESILIENCE',
    module: 'Cart & Checkout',
    scenario: 'A very long checkout Name is handled without crashing',
    type: 'Edge',
    priority: 'Low',
    preconditions: 'The cart contains at least one item.',
    testData: "name: 'a'.repeat(500)",
    steps: '1. Open "Place Order".\n2. Enter a 500-character Name.\n3. Submit.',
    expectedResult: 'The purchase completes (or is rejected) without crashing the page.',
    postconditions: 'Cart is empty.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@edge',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-25',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-26',
    requirementId: 'REQ-CART-CHECKOUT-VALIDATE',
    module: 'Cart & Checkout',
    scenario: 'A whitespace-only Card value bypasses required-field validation',
    type: 'Negative',
    priority: 'Low',
    preconditions: 'The cart contains at least one item.',
    testData: 'card: "   " (three spaces)',
    steps: '1. Open "Place Order".\n2. Fill Name; fill Card with only whitespace.\n3. Click "Purchase".',
    expectedResult: 'A trimming validator would treat this the same as an empty Card and raise the TC-CART-05 alert.',
    postconditions: 'Cart is empty.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@edge',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-26',
    observedResult:
      'The required-field check tests the raw string’s truthiness, not its trimmed content, so "   " counts as "filled": no alert fires, the purchase proceeds, and the confirmation then renders a blank Card Number.',
    executionStatus: 'Documented Finding',
    defectId: 'DEF-CART-05',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
  {
    id: 'TC-CART-27',
    requirementId: 'REQ-CART-VIEW',
    module: 'Cart & Checkout',
    scenario: 'The cart total correctly sums three items across three different categories',
    type: 'Functional',
    priority: 'Medium',
    preconditions: 'None.',
    testData: 'products: Samsung galaxy s6 (phone) + Sony vaio i5 (notebook) + Apple monitor 24 (monitor)',
    steps: '1. Clear the cart.\n2. Add one product from each of the phone, notebook, and monitor categories.\n3. Read the displayed total.',
    expectedResult: 'The total equals the exact sum of all three prices — deeper coverage than TC-CART-07’s two-item case, proving the sum isn’t coincidental.',
    postconditions: 'Cart contains three items.',
    automationStatus: 'Automated',
    layer: 'UI',
    suiteTags: '@regression',
    browserScope: ALL_PROJECTS,
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-27',
    observedResult: '',
    executionStatus: 'Pass',
    defectId: '',
    owner: OWNER,
    lastReviewed: REVIEWED,
  },
];
