export interface TestCaseRow {
  id: string;
  title: string;
  type: 'Functional' | 'Negative' | 'Edge' | 'Security';
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  preconditions: string;
  steps: string;
  testData: string;
  expectedResult: string;
  automated: 'Y' | 'N';
  automationRef: string;
}

/**
 * Every "Automated: Y" row corresponds 1:1 to a test in tests/ui/*.spec.ts —
 * the ID here is the same ID used in that spec's test title, so a reviewer
 * can trace a row straight to its implementation. "Automated: N" rows are
 * documented deliberately (either to avoid duplicating coverage of the same
 * code path, or because proving them safely requires a second isolated
 * account/context) rather than left out of the suite.
 */
export const LOGIN_TEST_CASES: TestCaseRow[] = [
  {
    id: 'TC-LOGIN-01',
    title: 'Valid credentials log the user in',
    type: 'Functional',
    priority: 'Critical',
    preconditions: 'A registered account exists (username/password known).',
    steps:
      '1. Open the home page.\n2. Click "Log in" in the nav bar.\n3. Enter a valid username and password.\n4. Click "Log in".',
    testData: 'username: <valid registered username>, password: <matching password>',
    expectedResult:
      'Modal closes; nav bar shows "Welcome <username>" and a "Log out" link; "Log in" link is hidden.',
    automated: 'Y',
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-01',
  },
  {
    id: 'TC-LOGIN-02',
    title: 'Logging out returns to the logged-out state',
    type: 'Functional',
    priority: 'High',
    preconditions: 'User is logged in.',
    steps: '1. Click "Log out" in the nav bar.',
    testData: 'n/a',
    expectedResult: '"Log in" / "Sign up" links reappear; the welcome label is hidden.',
    automated: 'Y',
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-02',
  },
  {
    id: 'TC-LOGIN-03',
    title: 'Session survives navigating to another page',
    type: 'Functional',
    priority: 'Medium',
    preconditions: 'User is logged in.',
    steps: '1. Log in.\n2. Click "Cart" in the nav bar.',
    testData: 'n/a',
    expectedResult: 'The cart page still shows "Welcome <username>" — login state is not lost on navigation.',
    automated: 'Y',
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-03',
  },
  {
    id: 'TC-LOGIN-04',
    title: 'A non-existent username is rejected',
    type: 'Negative',
    priority: 'High',
    preconditions: 'The chosen username does not exist in the system.',
    steps: '1. Open the login modal.\n2. Enter a username that has never been registered.\n3. Enter any password.\n4. Click "Log in".',
    testData: 'username: <random unregistered username>, password: irrelevant-password',
    expectedResult: 'An alert reading "User does not exist." is shown; the user is not logged in.',
    automated: 'Y',
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-04',
  },
  {
    id: 'TC-LOGIN-05',
    title: 'The correct username with the wrong password is rejected',
    type: 'Negative',
    priority: 'High',
    preconditions: 'A registered account exists.',
    steps: '1. Open the login modal.\n2. Enter the correct username.\n3. Enter an incorrect password.\n4. Click "Log in".',
    testData: 'username: <valid username>, password: <valid password> + "-wrong"',
    expectedResult: 'An alert reading "Wrong password." is shown; the user is not logged in.',
    automated: 'Y',
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-05',
  },
  {
    id: 'TC-LOGIN-06',
    title: 'Submitting with both fields empty is rejected client-side',
    type: 'Negative',
    priority: 'Medium',
    preconditions: 'None.',
    steps: '1. Open the login modal.\n2. Leave both fields empty.\n3. Click "Log in".',
    testData: 'username: "", password: ""',
    expectedResult:
      'An alert reading "Please fill out Username and Password." is shown before any network call; the modal stays open.',
    automated: 'Y',
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-06',
  },
  {
    id: 'TC-LOGIN-07',
    title: 'Submitting with only the password filled is rejected client-side',
    type: 'Negative',
    priority: 'Medium',
    preconditions: 'None.',
    steps: '1. Open the login modal.\n2. Leave username empty; fill in a password.\n3. Click "Log in".',
    testData: 'username: "", password: <valid password>',
    expectedResult: 'Same client-side validation alert as TC-LOGIN-06.',
    automated: 'Y',
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-07',
  },
  {
    id: 'TC-LOGIN-08',
    title: 'A SQL-injection-shaped username is treated as plain text, not exploited',
    type: 'Security',
    priority: 'High',
    preconditions: 'None.',
    steps: "1. Open the login modal.\n2. Enter ' OR '1'='1' -- in both fields.\n3. Click \"Log in\".",
    testData: "username: ' OR '1'='1' --, password: ' OR '1'='1' --",
    expectedResult:
      'Verified against the live site: no SQL error, no crash, and — critically — no bypassed login. (Actual observed behavior differs from the naive expectation of an alert: this specific input reproducibly causes a full page reload instead, likely an unhandled client-side exception on this response path. Either way the user ends up logged out on a fresh home page.)',
    automated: 'Y',
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-08',
  },
  {
    id: 'TC-LOGIN-09',
    title: 'A very long username is handled without crashing the page',
    type: 'Edge',
    priority: 'Low',
    preconditions: 'None.',
    steps: '1. Open the login modal.\n2. Enter a 500-character username.\n3. Click "Log in".',
    testData: "username: 'a'.repeat(500), password: irrelevant-password",
    expectedResult: 'An error alert is shown (not a crash); the page remains responsive.',
    automated: 'Y',
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-09',
  },
  {
    id: 'TC-LOGIN-10',
    title: 'Username lookup is case-sensitive',
    type: 'Edge',
    priority: 'Medium',
    preconditions: 'A registered account exists.',
    steps: '1. Open the login modal.\n2. Enter the registered username in uppercase.\n3. Enter the correct password.\n4. Click "Log in".',
    testData: 'username: <VALID USERNAME UPPERCASED>, password: <valid password>',
    expectedResult:
      'Rejected with "User does not exist." — documents actual behavior (no case-folding) rather than assuming it.',
    automated: 'Y',
    automationRef: 'tests/ui/login.spec.ts — TC-LOGIN-10',
  },
  {
    id: 'TC-LOGIN-11',
    title: 'Only username filled, password empty is rejected',
    type: 'Negative',
    priority: 'Low',
    preconditions: 'None.',
    steps: '1. Open the login modal.\n2. Fill in a username; leave password empty.\n3. Click "Log in".',
    testData: 'username: <valid username>, password: ""',
    expectedResult: 'Same "Please fill out Username and Password." alert as TC-LOGIN-06/07.',
    automated: 'N',
    automationRef: 'Not automated — symmetric case of TC-LOGIN-07, same client-side validation code path.',
  },
  {
    id: 'TC-LOGIN-12',
    title: 'Leading/trailing whitespace in credentials is treated literally (not trimmed)',
    type: 'Edge',
    priority: 'Low',
    preconditions: 'A registered account exists.',
    steps: '1. Open the login modal.\n2. Enter the valid username with a leading space.\n3. Enter the valid password.\n4. Click "Log in".',
    testData: 'username: " <valid username>", password: <valid password>',
    expectedResult: 'Rejected as an unknown user — the app does not trim whitespace before lookup.',
    automated: 'N',
    automationRef: 'Documented for manual/exploratory verification.',
  },
  {
    id: 'TC-LOGIN-13',
    title: 'Closing the login modal via the × button cancels without submitting',
    type: 'Functional',
    priority: 'Low',
    preconditions: 'None.',
    steps: '1. Open the login modal.\n2. Enter any credentials.\n3. Click the × close button instead of "Log in".',
    testData: 'n/a',
    expectedResult: 'Modal closes; no network request is made; user remains logged out.',
    automated: 'N',
    automationRef: 'Documented for manual/exploratory verification.',
  },
  {
    id: 'TC-LOGIN-14',
    title: 'An XSS-shaped username is rendered as inert text, not executed',
    type: 'Security',
    priority: 'Medium',
    preconditions: 'None.',
    steps: '1. Open the login modal.\n2. Enter <script>alert(1)</script> as the username.\n3. Submit.',
    testData: 'username: <script>alert(1)</script>',
    expectedResult: 'No script executes; the string is handled as an ordinary (rejected) username.',
    automated: 'N',
    automationRef: 'Documented for manual/exploratory verification — same family as TC-LOGIN-08.',
  },
  {
    id: 'TC-LOGIN-15',
    title: 'Password characters are masked in the input field',
    type: 'Functional',
    priority: 'Low',
    preconditions: 'None.',
    steps: '1. Open the login modal.\n2. Type into the password field.',
    testData: 'password: anything',
    expectedResult: 'Characters render as dots/asterisks, not plain text.',
    automated: 'N',
    automationRef: 'Documented for manual/exploratory verification (visual property, not a functional assertion).',
  },
  {
    id: 'TC-LOGIN-16',
    title: 'A Unicode/emoji username is handled without crashing',
    type: 'Edge',
    priority: 'Low',
    preconditions: 'None.',
    steps: '1. Open the login modal.\n2. Enter a username containing emoji/non-Latin characters.\n3. Submit.',
    testData: 'username: 用户🙂test',
    expectedResult: 'Rejected as an unknown user; page remains responsive, no crash.',
    automated: 'N',
    automationRef: 'Documented for manual/exploratory verification.',
  },
];

export const CART_TEST_CASES: TestCaseRow[] = [
  {
    id: 'TC-CART-01',
    title: 'Adding a product surfaces a confirmation and lists it in the cart',
    type: 'Functional',
    priority: 'Critical',
    preconditions: 'None (works whether logged in or as a guest).',
    steps: '1. Open a product page.\n2. Click "Add to cart".\n3. Navigate to the cart page.',
    testData: 'product: Samsung galaxy s6',
    expectedResult:
      'An alert confirms "Product added." (with or without trailing period — see README known-issue note); the product appears as a row in the cart.',
    automated: 'Y',
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-01',
  },
  {
    id: 'TC-CART-02',
    title: 'Full journey: log in, add to cart, place an order',
    type: 'Functional',
    priority: 'Critical',
    preconditions: 'A registered account exists.',
    steps:
      '1. Log in.\n2. Clear any pre-existing cart contents.\n3. Add a product to the cart.\n4. Open "Place Order".\n5. Fill in Name, Country, City, Card, Month, Year.\n6. Click "Purchase".',
    testData: 'product: Samsung galaxy s6; name: QA Automation; card: 4111111111111111; month: 12; year: 2030',
    expectedResult:
      'Cart total equals the product price; the Place Order total matches; purchase succeeds and shows a confirmation with a non-empty order ID, the correct amount, and the entered name.',
    automated: 'Y',
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-02 (primary end-to-end demo scenario)',
  },
  {
    id: 'TC-CART-03',
    title: 'Adding the same product twice creates two separate line items',
    type: 'Edge',
    priority: 'Medium',
    preconditions: 'None.',
    steps: '1. Open a product page.\n2. Click "Add to cart" twice in a row.\n3. Open the cart.',
    testData: 'product: Apple monitor 24',
    expectedResult:
      'Two separate rows for the same product appear — demoblaze has no quantity/merge concept, documented rather than assumed.',
    automated: 'Y',
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-03',
  },
  {
    id: 'TC-CART-04',
    title: 'Deleting an item removes it from the cart',
    type: 'Functional',
    priority: 'High',
    preconditions: 'The cart contains at least one item.',
    steps: '1. Open the cart.\n2. Click "Delete" on a row.',
    testData: 'product: Sony vaio i5',
    expectedResult: 'The row disappears and the cart row count decreases by one.',
    automated: 'Y',
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-04',
  },
  {
    id: 'TC-CART-05',
    title: 'Placing an order with Name and Card empty is rejected client-side',
    type: 'Negative',
    priority: 'High',
    preconditions: 'The cart contains at least one item.',
    steps: '1. Open "Place Order".\n2. Fill only Country/City/Month/Year; leave Name and Card blank.\n3. Click "Purchase".',
    testData: 'name: "", card: ""',
    expectedResult:
      'An alert reading "Please fill out Name and Creditcard." is shown; no confirmation dialog appears.',
    automated: 'Y',
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-05',
  },
  {
    id: 'TC-CART-06',
    title: 'Optional address/date fields can be left blank',
    type: 'Functional',
    priority: 'Medium',
    preconditions: 'The cart contains at least one item.',
    steps: '1. Open "Place Order".\n2. Fill only Name and Card; leave Country/City/Month/Year blank.\n3. Click "Purchase".',
    testData: 'name: Minimal Fields, card: 4111111111111111',
    expectedResult: 'Purchase succeeds; the confirmation shows the entered name — only Name/Card are truly required.',
    automated: 'Y',
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-06',
  },
  {
    id: 'TC-CART-07',
    title: "The cart total equals the sum of its own line items",
    type: 'Functional',
    priority: 'Medium',
    preconditions: 'None.',
    steps: '1. Clear the cart.\n2. Add one product.\n3. Open the cart and read the displayed total.',
    testData: 'product: Samsung galaxy s6',
    expectedResult: "The displayed total exactly equals that product's price.",
    automated: 'Y',
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-07',
  },
  {
    id: 'TC-CART-08',
    title: 'The cart is reachable without being logged in',
    type: 'Edge',
    priority: 'Medium',
    preconditions: 'User is logged out.',
    steps: '1. Navigate directly to /cart.html as a guest.',
    testData: 'n/a',
    expectedResult: 'The cart page renders (total label visible) without requiring authentication.',
    automated: 'Y',
    automationRef: 'tests/ui/cart.spec.ts — TC-CART-08',
  },
  {
    id: 'TC-CART-09',
    title: 'A non-numeric card number is still accepted',
    type: 'Negative',
    priority: 'Low',
    preconditions: 'The cart contains at least one item.',
    steps: '1. Open "Place Order".\n2. Fill Name and enter a non-numeric string as Card.\n3. Click "Purchase".',
    testData: 'card: "not-a-card-number"',
    expectedResult:
      'Purchase still succeeds — documents an actual application weakness (no card-format validation), not an assumption.',
    automated: 'N',
    automationRef: 'Documented finding — candidate for future automation once product owner confirms expected behavior.',
  },
  {
    id: 'TC-CART-10',
    title: 'An already-expired card year is still accepted',
    type: 'Negative',
    priority: 'Low',
    preconditions: 'The cart contains at least one item.',
    steps: '1. Open "Place Order".\n2. Fill Name/Card, set Year to a year in the past.\n3. Click "Purchase".',
    testData: 'year: 2010',
    expectedResult: 'Purchase still succeeds — no expiry validation exists.',
    automated: 'N',
    automationRef: 'Documented finding — same category as TC-CART-09.',
  },
  {
    id: 'TC-CART-11',
    title: 'Deleting the only remaining item empties the cart',
    type: 'Functional',
    priority: 'Low',
    preconditions: 'The cart contains exactly one item.',
    steps: '1. Delete the last remaining row.',
    testData: 'n/a',
    expectedResult: 'The row list is empty and the total shows 0 (or blank).',
    automated: 'N',
    automationRef: 'Conceptually covered by removeAllItems() used as setup in TC-CART-02/07; not asserted as its own case.',
  },
  {
    id: 'TC-CART-12',
    title: "The cart is a single shared list, not scoped per visitor session",
    type: 'Edge',
    priority: 'Medium',
    preconditions: 'None.',
    steps: '1. Load the cart from two different, unauthenticated browser contexts.',
    testData: 'n/a',
    expectedResult:
      'Both contexts see the same underlying item list — a verified environment characteristic of the public demo (see README "Known environment characteristics"), not a framework limitation.',
    automated: 'N',
    automationRef: 'Documented finding — proving it without disturbing other testers’ concurrent runs is out of scope for CI.',
  },
  {
    id: 'TC-CART-13',
    title: 'Product page price matches the price shown in the cart row',
    type: 'Functional',
    priority: 'Low',
    preconditions: 'None.',
    steps: '1. Read the price on a product page.\n2. Add it to the cart.\n3. Compare against the price shown in the cart row.',
    testData: 'product: Samsung galaxy s6',
    expectedResult: 'The two prices match exactly.',
    automated: 'N',
    automationRef: 'Implicitly covered by the price-equality assertions in TC-CART-02.',
  },
  {
    id: 'TC-CART-14',
    title: 'Opening "Place Order" on an empty cart is not blocked',
    type: 'Negative',
    priority: 'Low',
    preconditions: 'The cart has been cleared.',
    steps: '1. Clear the cart.\n2. Click "Place Order".',
    testData: 'n/a',
    expectedResult: 'The modal still opens with a total of 0 — there is no "cart is empty" guard.',
    automated: 'N',
    automationRef: 'Documented finding — candidate for future automation.',
  },
];
